"""add recruitment radar public models

Revision ID: 8418f8d1585a
Revises: d8cf04cfe08c
Create Date: 2026-08-18 17:32:16.109775
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8418f8d1585a'
down_revision: Union[str, None] = 'd8cf04cfe08c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recruitment_campaign',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('campaign_key', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('season', sa.Text(), nullable=False),
    sa.Column('campaign_year', sa.Integer(), nullable=True),
    sa.Column('recruitment_type', sa.Text(), nullable=False),
    sa.Column('internship_type', sa.Text(), nullable=False),
    sa.Column('graduation_years_status', sa.Text(), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('official_url', sa.Text(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('classification_evidence', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.CheckConstraint("internship_type IN ('not_applicable', 'summer', 'daily', 'winter', 'unknown')", name='chk_campaign_internship_type'),
    sa.CheckConstraint("graduation_years_status IN ('known', 'unknown')", name='chk_campaign_graduation_years_status'),
    sa.CheckConstraint("recruitment_type IN ('campus_full_time', 'graduate_program', 'internship', 'unknown')", name='chk_campaign_recruitment_type'),
    sa.CheckConstraint("season IN ('autumn', 'spring', 'early', 'makeup', 'rolling', 'unknown')", name='chk_campaign_season'),
    sa.CheckConstraint("status IN ('upcoming', 'active', 'closed', 'unknown')", name='chk_campaign_status'),
    sa.CheckConstraint('campaign_year IS NULL OR (campaign_year >= 2000 AND campaign_year <= 2200)', name='chk_campaign_year'),
    sa.CheckConstraint('classification_confidence IS NULL OR (classification_confidence >= 0 AND classification_confidence <= 1)', name='chk_campaign_confidence'),
    sa.CheckConstraint('last_seen_at >= first_seen_at', name='chk_campaign_seen_order'),
    sa.CheckConstraint('start_at IS NULL OR deadline IS NULL OR deadline >= start_at', name='chk_campaign_date_order'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'company_id', name='uq_campaign_identity_scope')
    )
    with op.batch_alter_table('recruitment_campaign', schema=None) as batch_op:
        batch_op.create_index('idx_campaign_company_status', ['company_id', 'status'], unique=False)
        batch_op.create_index('idx_campaign_deadline', ['deadline'], unique=False, sqlite_where=sa.text('deadline IS NOT NULL'), postgresql_where=sa.text('deadline IS NOT NULL'))
        batch_op.create_index('idx_campaign_source_key', ['company_id', 'campaign_key'], unique=True)

    op.create_table('campaign_graduation_year',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=False),
    sa.CheckConstraint('graduation_year >= 2000 AND graduation_year <= 2200', name='chk_campaign_graduation_year'),
    sa.ForeignKeyConstraint(['campaign_id'], ['recruitment_campaign.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('campaign_id', 'graduation_year')
    )
    with op.batch_alter_table('campaign_graduation_year', schema=None) as batch_op:
        batch_op.create_index('idx_campaign_graduation_year_lookup', ['graduation_year', 'campaign_id'], unique=False)

    op.create_table('source_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('run_key', sa.Text(), nullable=False),
    sa.Column('crawl_log_id', sa.Integer(), nullable=True),
    sa.Column('previous_valid_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('is_baseline', sa.Boolean(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('source_total', sa.Integer(), nullable=True),
    sa.Column('fetched_total', sa.Integer(), nullable=False),
    sa.Column('indexed_total', sa.Integer(), nullable=False),
    sa.Column('excluded_total', sa.Integer(), nullable=False),
    sa.Column('failed_total', sa.Integer(), nullable=False),
    sa.Column('position_keys', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('position_set_hash', sa.Text(), nullable=True),
    sa.Column('response_hash', sa.Text(), nullable=True),
    sa.Column('parser_version', sa.Text(), nullable=False),
    sa.Column('completeness_status', sa.Text(), nullable=False),
    sa.Column('comparison_status', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.CheckConstraint("comparison_status IN ('pending', 'baseline', 'compared', 'suppressed', 'failed')", name='chk_snapshot_comparison_status'),
    sa.CheckConstraint("(comparison_status = 'baseline' AND is_baseline = TRUE) OR (comparison_status <> 'baseline' AND is_baseline = FALSE)", name='chk_snapshot_baseline_identity'),
    sa.CheckConstraint("comparison_status <> 'baseline' OR (status = 'success' AND completeness_status IN ('count_matched', 'pagination_verified') AND previous_valid_snapshot_id IS NULL)", name='chk_snapshot_baseline_valid'),
    sa.CheckConstraint("comparison_status <> 'compared' OR (status = 'success' AND completeness_status IN ('count_matched', 'pagination_verified') AND previous_valid_snapshot_id IS NOT NULL AND is_baseline = FALSE)", name='chk_snapshot_compared_valid'),
    sa.CheckConstraint("status <> 'failed' OR comparison_status = 'failed'", name='chk_snapshot_failed_comparison'),
    sa.CheckConstraint("completeness_status IN ('count_matched', 'pagination_verified', 'incomplete', 'failed')", name='chk_snapshot_completeness_status'),
    sa.CheckConstraint("status IN ('success', 'failed')", name='chk_snapshot_status'),
    sa.CheckConstraint('(source_total IS NULL OR source_total >= 0) AND fetched_total >= 0 AND indexed_total >= 0 AND excluded_total >= 0 AND failed_total >= 0', name='chk_snapshot_counts'),
    sa.CheckConstraint('fetched_total = indexed_total + excluded_total + failed_total', name='chk_snapshot_accounted_counts'),
    sa.CheckConstraint("completeness_status <> 'count_matched' OR (source_total IS NOT NULL AND source_total = fetched_total)", name='chk_snapshot_source_total_matched'),
    sa.CheckConstraint("comparison_status NOT IN ('baseline', 'compared') OR (completed_at IS NOT NULL AND position_set_hash IS NOT NULL)", name='chk_snapshot_comparison_evidence'),
    sa.CheckConstraint('completed_at IS NULL OR completed_at >= fetched_at', name='chk_snapshot_time_order'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['crawl_log_id'], ['crawl_log.id'], ),
    sa.ForeignKeyConstraint(['previous_valid_snapshot_id', 'company_id', 'source_id'], ['source_snapshot.id', 'source_snapshot.company_id', 'source_snapshot.source_id'], name='fk_snapshot_previous_scope'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'company_id', 'source_id', name='uq_snapshot_identity_scope')
    )
    with op.batch_alter_table('source_snapshot', schema=None) as batch_op:
        batch_op.create_index('idx_snapshot_company_fetched', ['company_id', 'fetched_at'], unique=False)
        batch_op.create_index('idx_snapshot_one_baseline_per_source', ['source_id'], unique=True, sqlite_where=sa.text("comparison_status = 'baseline'"), postgresql_where=sa.text("comparison_status = 'baseline'"))
        batch_op.create_index('idx_snapshot_one_comparison_per_previous', ['previous_valid_snapshot_id'], unique=True, sqlite_where=sa.text("comparison_status = 'compared'"), postgresql_where=sa.text("comparison_status = 'compared'"))
        batch_op.create_index('idx_snapshot_previous_valid', ['previous_valid_snapshot_id'], unique=False)
        batch_op.create_index('idx_snapshot_source_fetched', ['source_id', 'fetched_at'], unique=False)
        batch_op.create_index('idx_snapshot_source_run_key', ['source_id', 'run_key'], unique=True)
        batch_op.create_index('idx_snapshot_status', ['status', 'completeness_status'], unique=False)

    op.create_table('company_change_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('dedup_key', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('added_count', sa.Integer(), nullable=False),
    sa.Column('reopened_count', sa.Integer(), nullable=False),
    sa.Column('closed_count', sa.Integer(), nullable=False),
    sa.Column('changed_count', sa.Integer(), nullable=False),
    sa.Column('reporting_date_cn', sa.Date(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('computation_status', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.CheckConstraint("computation_status IN ('computed', 'suppressed', 'review_required')", name='chk_company_change_computation_status'),
    sa.CheckConstraint("event_type IN ('campaign_started', 'campaign_updated', 'campaign_closed', 'positions_changed', 'position_reopened', 'page_updated', 'source_degraded', 'source_recovered')", name='chk_company_change_event_type'),
    sa.CheckConstraint('added_count >= 0 AND reopened_count >= 0 AND closed_count >= 0 AND changed_count >= 0', name='chk_company_change_counts'),
    sa.CheckConstraint("event_type <> 'positions_changed' OR (added_count + closed_count + changed_count > 0 AND reopened_count = 0)", name='chk_company_change_positions_counts'),
    sa.CheckConstraint("event_type <> 'position_reopened' OR (reopened_count > 0 AND added_count = 0 AND closed_count = 0 AND changed_count = 0)", name='chk_company_change_reopened_counts'),
    sa.CheckConstraint("event_type IN ('positions_changed', 'position_reopened') OR (added_count = 0 AND reopened_count = 0 AND closed_count = 0 AND changed_count = 0)", name='chk_company_change_non_position_counts'),
    sa.CheckConstraint("event_type NOT IN ('campaign_started', 'campaign_updated', 'campaign_closed') OR campaign_id IS NOT NULL", name='chk_company_change_campaign_required'),
    sa.ForeignKeyConstraint(['campaign_id', 'company_id'], ['recruitment_campaign.id', 'recruitment_campaign.company_id'], name='fk_company_change_campaign_scope'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id', 'company_id', 'source_id'], ['source_snapshot.id', 'source_snapshot.company_id', 'source_snapshot.source_id'], name='fk_company_change_snapshot_scope'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_key')
    )
    with op.batch_alter_table('company_change_event', schema=None) as batch_op:
        batch_op.create_index('idx_company_change_company', ['company_id', 'occurred_at'], unique=False)
        batch_op.create_index('idx_company_change_date', ['reporting_date_cn', 'event_type'], unique=False)
        batch_op.create_index('idx_company_change_snapshot', ['snapshot_id'], unique=False)

    op.create_table('observed_position_ref',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('dedupe_key', sa.Text(), nullable=False),
    sa.Column('identity_kind', sa.Text(), nullable=False),
    sa.Column('external_job_id', sa.Text(), nullable=True),
    sa.Column('canonical_url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('locations', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('recruitment_type', sa.Text(), nullable=False),
    sa.Column('internship_type', sa.Text(), nullable=False),
    sa.Column('graduation_years', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('content_fingerprint', sa.Text(), nullable=False),
    sa.Column('missing_count', sa.Integer(), nullable=False),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('classification_evidence', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.CheckConstraint("internship_type IN ('not_applicable', 'summer', 'daily', 'winter', 'unknown')", name='chk_position_ref_internship_type'),
    sa.CheckConstraint("identity_kind IN ('external_id', 'canonical_url', 'fingerprint')", name='chk_position_ref_identity_kind'),
    sa.CheckConstraint("(identity_kind <> 'external_id' OR external_job_id IS NOT NULL) AND (identity_kind <> 'canonical_url' OR canonical_url IS NOT NULL)", name='chk_position_ref_identity_evidence'),
    sa.CheckConstraint("recruitment_type IN ('campus_full_time', 'graduate_program', 'internship', 'unknown')", name='chk_position_ref_recruitment_type'),
    sa.CheckConstraint("status IN ('open', 'closed', 'unknown')", name='chk_position_ref_status'),
    sa.CheckConstraint('classification_confidence IS NULL OR (classification_confidence >= 0 AND classification_confidence <= 1)', name='chk_position_ref_confidence'),
    sa.CheckConstraint('missing_count >= 0', name='chk_position_ref_missing_count'),
    sa.CheckConstraint('last_seen_at >= first_seen_at', name='chk_position_ref_seen_order'),
    sa.CheckConstraint("(status = 'closed' AND closed_at IS NOT NULL) OR (status <> 'closed' AND closed_at IS NULL)", name='chk_position_ref_closed_time'),
    sa.ForeignKeyConstraint(['campaign_id', 'company_id'], ['recruitment_campaign.id', 'recruitment_campaign.company_id'], name='fk_position_ref_campaign_scope'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('observed_position_ref', schema=None) as batch_op:
        batch_op.create_index('idx_position_ref_campaign', ['campaign_id'], unique=False)
        batch_op.create_index('idx_position_ref_company_status', ['company_id', 'status'], unique=False)
        batch_op.create_index('idx_position_ref_last_seen', ['source_id', 'last_seen_at'], unique=False)
        batch_op.create_index('idx_position_ref_source_dedupe', ['source_id', 'dedupe_key'], unique=True)

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_company_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('registry_id', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('aliases', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))
        batch_op.add_column(sa.Column('ownership_type', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Text(), server_default=sa.text("'candidate'"), nullable=False))
        batch_op.add_column(sa.Column('first_verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_observed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.create_check_constraint(
            'chk_company_status',
            "status IN ('candidate', 'verified', 'monitoring', 'paused', 'retired')",
        )
        batch_op.create_check_constraint(
            'chk_company_not_own_parent',
            'parent_company_id IS NULL OR parent_company_id <> id',
        )
        batch_op.create_check_constraint(
            'chk_company_verified_timestamp',
            "status NOT IN ('verified', 'monitoring') OR first_verified_at IS NOT NULL",
        )
        batch_op.create_foreign_key(
            'fk_company_parent',
            'company',
            ['parent_company_id'],
            ['id'],
        )
        batch_op.create_index('idx_company_first_verified_at', ['first_verified_at'], unique=False, sqlite_where=sa.text('first_verified_at IS NOT NULL'), postgresql_where=sa.text('first_verified_at IS NOT NULL'))
        batch_op.create_index('idx_company_parent', ['parent_company_id'], unique=False)
        batch_op.create_index('idx_company_registry_id', ['registry_id'], unique=True, sqlite_where=sa.text('registry_id IS NOT NULL'), postgresql_where=sa.text('registry_id IS NOT NULL'))
        batch_op.create_index('idx_company_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index('idx_company_status')
        batch_op.drop_index('idx_company_registry_id', sqlite_where=sa.text('registry_id IS NOT NULL'), postgresql_where=sa.text('registry_id IS NOT NULL'))
        batch_op.drop_index('idx_company_first_verified_at', sqlite_where=sa.text('first_verified_at IS NOT NULL'), postgresql_where=sa.text('first_verified_at IS NOT NULL'))
        batch_op.drop_index('idx_company_parent')
        batch_op.drop_constraint('fk_company_parent', type_='foreignkey')
        batch_op.drop_constraint('chk_company_verified_timestamp', type_='check')
        batch_op.drop_constraint('chk_company_not_own_parent', type_='check')
        batch_op.drop_constraint('chk_company_status', type_='check')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('last_observed_at')
        batch_op.drop_column('first_verified_at')
        batch_op.drop_column('status')
        batch_op.drop_column('ownership_type')
        batch_op.drop_column('aliases')
        batch_op.drop_column('registry_id')
        batch_op.drop_column('parent_company_id')

    with op.batch_alter_table('observed_position_ref', schema=None) as batch_op:
        batch_op.drop_index('idx_position_ref_source_dedupe')
        batch_op.drop_index('idx_position_ref_last_seen')
        batch_op.drop_index('idx_position_ref_company_status')
        batch_op.drop_index('idx_position_ref_campaign')

    op.drop_table('observed_position_ref')
    with op.batch_alter_table('company_change_event', schema=None) as batch_op:
        batch_op.drop_index('idx_company_change_snapshot')
        batch_op.drop_index('idx_company_change_date')
        batch_op.drop_index('idx_company_change_company')

    op.drop_table('company_change_event')
    with op.batch_alter_table('source_snapshot', schema=None) as batch_op:
        batch_op.drop_index('idx_snapshot_status')
        batch_op.drop_index('idx_snapshot_source_run_key')
        batch_op.drop_index('idx_snapshot_source_fetched')
        batch_op.drop_index('idx_snapshot_previous_valid')
        batch_op.drop_index('idx_snapshot_one_comparison_per_previous', sqlite_where=sa.text("comparison_status = 'compared'"), postgresql_where=sa.text("comparison_status = 'compared'"))
        batch_op.drop_index('idx_snapshot_one_baseline_per_source', sqlite_where=sa.text("comparison_status = 'baseline'"), postgresql_where=sa.text("comparison_status = 'baseline'"))
        batch_op.drop_index('idx_snapshot_company_fetched')

    op.drop_table('source_snapshot')
    with op.batch_alter_table('campaign_graduation_year', schema=None) as batch_op:
        batch_op.drop_index('idx_campaign_graduation_year_lookup')

    op.drop_table('campaign_graduation_year')
    with op.batch_alter_table('recruitment_campaign', schema=None) as batch_op:
        batch_op.drop_index('idx_campaign_source_key')
        batch_op.drop_index('idx_campaign_deadline', sqlite_where=sa.text('deadline IS NOT NULL'), postgresql_where=sa.text('deadline IS NOT NULL'))
        batch_op.drop_index('idx_campaign_company_status')

    op.drop_table('recruitment_campaign')
    # ### end Alembic commands ###
