"""existing schema baseline

Revision ID: d8cf04cfe08c
Revises:
Create Date: 2026-08-18 17:29:59.683238
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd8cf04cfe08c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('industry', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_index('idx_company_category', ['category'], unique=False, sqlite_where=sa.text('category IS NOT NULL'), postgresql_where=sa.text('category IS NOT NULL'))

    op.create_table('crawl_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('success', 'failed', 'skipped')", name='chk_crawl_status'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crawl_log', schema=None) as batch_op:
        batch_op.create_index('idx_crawl_source', ['source'], unique=False)
        batch_op.create_index('idx_crawl_started_at', ['started_at'], unique=False)
        batch_op.create_index('idx_crawl_status', ['status'], unique=False)

    op.create_table('job',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('salary', sa.Text(), nullable=True),
    sa.Column('jd', sa.Text(), nullable=True),
    sa.Column('requirement', sa.Text(), nullable=True),
    sa.Column('apply_url', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('job_category', sa.Text(), nullable=True),
    sa.Column('graduation_year', sa.Text(), nullable=True),
    sa.Column('education', sa.Text(), nullable=True),
    sa.Column('experience', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('is_intern', sa.Boolean(), nullable=False),
    sa.Column('is_fresh', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.CheckConstraint("status IN ('displaying', 'closed')", name='chk_job_status'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index('idx_job_category', ['job_category'], unique=False, sqlite_where=sa.text('job_category IS NOT NULL'), postgresql_where=sa.text('job_category IS NOT NULL'))
        batch_op.create_index('idx_job_collected_at', ['collected_at'], unique=False)
        batch_op.create_index('idx_job_company', ['company'], unique=False)
        batch_op.create_index('idx_job_deadline', ['deadline'], unique=False, sqlite_where=sa.text('deadline IS NOT NULL'), postgresql_where=sa.text('deadline IS NOT NULL'))
        batch_op.create_index('idx_job_dedup', ['source', 'company', 'title', 'location'], unique=True)
        batch_op.create_index('idx_job_source', ['source'], unique=False)
        batch_op.create_index('idx_job_status', ['status'], unique=False)

    op.create_table('subscription',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword', sa.Text(), nullable=True),
    sa.Column('company', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.create_index('idx_sub_company', ['company'], unique=False, sqlite_where=sa.text('company IS NOT NULL'), postgresql_where=sa.text('company IS NOT NULL'))
        batch_op.create_index('idx_sub_keyword', ['keyword'], unique=False, sqlite_where=sa.text('keyword IS NOT NULL'), postgresql_where=sa.text('keyword IS NOT NULL'))

    op.create_table('application',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('applied', 'test', 'interviewing', 'offer_pending', 'offer_accepted', 'offer_declined', 'rejected', 'no_response', 'withdrawn')", name='chk_app_status'),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.create_index('idx_app_applied_at', ['applied_at'], unique=False)
        batch_op.create_index('idx_app_job_id', ['job_id'], unique=False)
        batch_op.create_index('idx_app_one_active_per_job', ['job_id'], unique=True, sqlite_where=sa.text("status NOT IN ('rejected','withdrawn','no_response','offer_accepted','offer_declined')"), postgresql_where=sa.text("status NOT IN ('rejected','withdrawn','no_response','offer_accepted','offer_declined')"))
        batch_op.create_index('idx_app_status', ['status'], unique=False)
        batch_op.create_index('idx_app_updated_at', ['updated_at'], unique=False)

    op.create_table('user_job_action',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("action_type IN ('favorited', 'to_apply')", name='chk_uja_action_type'),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_job_action', schema=None) as batch_op:
        batch_op.create_index('idx_uja_action_type', ['action_type'], unique=False)
        batch_op.create_index('idx_uja_active', ['job_id', 'action_type'], unique=False, sqlite_where=sa.text('ended_at IS NULL'), postgresql_where=sa.text('ended_at IS NULL'))
        batch_op.create_index('idx_uja_job_id', ['job_id'], unique=False)

    op.create_table('application_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('from_status', sa.Text(), nullable=True),
    sa.Column('to_status', sa.Text(), nullable=True),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.Column('is_correction', sa.Boolean(), nullable=False),
    sa.Column('correction_reason', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.CheckConstraint("event_type IN ('status_change', 'interview', 'test', 'material_submit', 'offer', 'note', 'correction')", name='chk_event_type'),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_event', schema=None) as batch_op:
        batch_op.create_index('idx_event_app_id', ['application_id', 'occurred_at'], unique=False)
        batch_op.create_index('idx_event_correction', ['application_id'], unique=False, sqlite_where=sa.text('is_correction = TRUE'), postgresql_where=sa.text('is_correction = TRUE'))
        batch_op.create_index('idx_event_funnel', ['event_type', 'to_status'], unique=False, sqlite_where=sa.text('is_correction = FALSE'), postgresql_where=sa.text('is_correction = FALSE'))
        batch_op.create_index('idx_event_todo', ['event_type', 'scheduled_at'], unique=False, sqlite_where=sa.text('scheduled_at IS NOT NULL AND occurred_at IS NULL'), postgresql_where=sa.text('scheduled_at IS NOT NULL AND occurred_at IS NULL'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_event', schema=None) as batch_op:
        batch_op.drop_index('idx_event_todo', sqlite_where=sa.text('scheduled_at IS NOT NULL AND occurred_at IS NULL'), postgresql_where=sa.text('scheduled_at IS NOT NULL AND occurred_at IS NULL'))
        batch_op.drop_index('idx_event_funnel', sqlite_where=sa.text('is_correction = FALSE'), postgresql_where=sa.text('is_correction = FALSE'))
        batch_op.drop_index('idx_event_correction', sqlite_where=sa.text('is_correction = TRUE'), postgresql_where=sa.text('is_correction = TRUE'))
        batch_op.drop_index('idx_event_app_id')

    op.drop_table('application_event')
    with op.batch_alter_table('user_job_action', schema=None) as batch_op:
        batch_op.drop_index('idx_uja_job_id')
        batch_op.drop_index('idx_uja_active', sqlite_where=sa.text('ended_at IS NULL'), postgresql_where=sa.text('ended_at IS NULL'))
        batch_op.drop_index('idx_uja_action_type')

    op.drop_table('user_job_action')
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_index('idx_app_updated_at')
        batch_op.drop_index('idx_app_status')
        batch_op.drop_index('idx_app_one_active_per_job', sqlite_where=sa.text("status NOT IN ('rejected','withdrawn','no_response','offer_accepted','offer_declined')"), postgresql_where=sa.text("status NOT IN ('rejected','withdrawn','no_response','offer_accepted','offer_declined')"))
        batch_op.drop_index('idx_app_job_id')
        batch_op.drop_index('idx_app_applied_at')

    op.drop_table('application')
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_index('idx_sub_keyword', sqlite_where=sa.text('keyword IS NOT NULL'), postgresql_where=sa.text('keyword IS NOT NULL'))
        batch_op.drop_index('idx_sub_company', sqlite_where=sa.text('company IS NOT NULL'), postgresql_where=sa.text('company IS NOT NULL'))

    op.drop_table('subscription')
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index('idx_job_status')
        batch_op.drop_index('idx_job_source')
        batch_op.drop_index('idx_job_dedup')
        batch_op.drop_index('idx_job_deadline', sqlite_where=sa.text('deadline IS NOT NULL'), postgresql_where=sa.text('deadline IS NOT NULL'))
        batch_op.drop_index('idx_job_company')
        batch_op.drop_index('idx_job_collected_at')
        batch_op.drop_index('idx_job_category', sqlite_where=sa.text('job_category IS NOT NULL'), postgresql_where=sa.text('job_category IS NOT NULL'))

    op.drop_table('job')
    with op.batch_alter_table('crawl_log', schema=None) as batch_op:
        batch_op.drop_index('idx_crawl_status')
        batch_op.drop_index('idx_crawl_started_at')
        batch_op.drop_index('idx_crawl_source')

    op.drop_table('crawl_log')
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index('idx_company_category', sqlite_where=sa.text('category IS NOT NULL'), postgresql_where=sa.text('category IS NOT NULL'))

    op.drop_table('company')
    # ### end Alembic commands ###
